## Data Cleaning

> Handle missing data

> Remove duplicate data entries

> Encode / Map the data

# Rules for missing data

> Either fill the missing values of the column (done when number of missing values in a column is very low, say 10%)

> Or Drop the whole column which has missing values (done when number of missing values in a column is large, say more than 30-40%)

Import Pandas library

In [34]:
import pandas as pd

Read the csv file, it creates a dataframe and adds a column at the start called "unnamed".

In [35]:
df=pd.read_csv('Titanic.csv')

Prints the dataframe structure with first 5 data entries

In [36]:
df.head()

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [37]:
df.shape

(891, 16)

.info() function gives total entries of each column. Used to compare with total entries in the data frame and choose which missing values to fill and which columns to drop.

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   sex          891 non-null    object
 4   age          714 non-null    float64
 5   sibsp        891 non-null    int64
 6   parch        891 non-null    int64
 7   fare         891 non-null    float64
 8   embarked     889 non-null    object
 9   class        891 non-null    object
 10  who          891 non-null    object
 11  adult_male   891 non-null    bool
 12  deck         203 non-null    object
 13  embark_town  889 non-null    object
 14  alive        891 non-null    object
 15  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(5), object(7)
memory usage: 99.3+ KB

We will fill values in the following columns:-
1. age column
2. embarked column
3. embarked_town column

We will drop the following columns:-
1. deck column

We also need to convert every column's data types to numerical value.

In [39]:
#df.drop('Unnamed: 0')
#Throws an error as it is looking for this name in rows, we need to look for it in column.

axis parameter is used to switch between:-
1. 0 (by default) -> horizontal axis (rows)
2. 1 -> vertical axis (columns)

In [40]:
df.drop('Unnamed: 0',axis=1) #.drop() function returns a new object, these changes are not saved

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [41]:
df.info() #We will still get the "Unnamed: 0" column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   sex          891 non-null    object
 4   age          714 non-null    float64
 5   sibsp        891 non-null    int64
 6   parch        891 non-null    int64
 7   fare         891 non-null    float64
 8   embarked     889 non-null    object
 9   class        891 non-null    object
 10  who          891 non-null    object
 11  adult_male   891 non-null    bool
 12  deck         203 non-null    object
 13  embark_town  889 non-null    object
 14  alive        891 non-null    object
 15  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(5), object(7)
memory usage: 99.3+ KB

In [42]:
df.drop("Unnamed: 0",axis=1,inplace=True) #This means df=df.drop("Unnamed: 0",axis=1)

In [43]:
df.info() #This doesn't included the dropped column as we put "inplace" as True. By default it is False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

In [44]:
df.drop("deck",axis=1,inplace=True)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(6)
memory usage: 85.4+ KB

.fillna() function is used to fill Na/NaN values with a value we provide.

In [46]:
df["age"].fillna(df["age"].mean(),inplace=True) #We find the mean using the mean() function on a column.It returns a single value

/tmp/ipykernel_4411/683578151.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(),inplace=True) #We find the mean using the mean() function on a column.It returns a single value

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(6)
memory usage: 85.4+ KB

1. df["age"].mean() -> returns a single value which is the mean of that column

2. df["age"].median() -> returns a single value which is the median of that column
3. df["age"].mode() -> returns an object with 0 as the key and the most occurring value as the value.

In [48]:
df['embarked'].mode() #gives key value pair of 0 and most occurring embarked value respectively

0    S
Name: embarked, dtype: object

In [49]:
df['embarked'].fillna( df['embarked'].mode()[0] , inplace=True)

/tmp/ipykernel_4411/1154257886.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna( df['embarked'].mode()[0] , inplace=True)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     891 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(6)
memory usage: 85.4+ KB

In [51]:
df['embark_town'].fillna( df['embark_town'].mode()[0] , inplace=True )

/tmp/ipykernel_4411/3101436441.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embark_town'].fillna( df['embark_town'].mode()[0] , inplace=True )

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     891 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  891 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(6)
memory usage: 85.4+ KB

In [53]:
df["age"].isnull().sum()
#.isnull() gives True for null values and False for non-null values
#.sum() interprets True as 1 and False as 0 and sums, hence this returns the count of null values

np.int64(0)

In [54]:
df.duplicated().sum() #Gives the sum of duplicate data entries

np.int64(111)

In [55]:
df.drop_duplicates(inplace=True)

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df.shape

(780, 14)

Encoding and Mapping are used to change objects or strings or other datatypes to numerical values.

In [58]:
df['sex']=df['sex'].map({"male":1, "female":0})

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     780 non-null    int64
 1   pclass       780 non-null    int64
 2   sex          780 non-null    int64
 3   age          780 non-null    float64
 4   sibsp        780 non-null    int64
 5   parch        780 non-null    int64
 6   fare         780 non-null    float64
 7   embarked     780 non-null    object
 8   class        780 non-null    object
 9   who          780 non-null    object
 10  adult_male   780 non-null    bool
 11  embark_town  780 non-null    object
 12  alive        780 non-null    object
 13  alone        780 non-null    bool
dtypes: bool(2), float64(2), int64(5), object(5)
memory usage: 80.7+ KB

In [60]:
df['adult_male']=df['adult_male'].astype(int) #Typecasting of the whole column.
df['alone']=df['alone'].astype(int) #Only done of boolean as its typecasted to 1 and 0 automatically.

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     780 non-null    int64
 1   pclass       780 non-null    int64
 2   sex          780 non-null    int64
 3   age          780 non-null    float64
 4   sibsp        780 non-null    int64
 5   parch        780 non-null    int64
 6   fare         780 non-null    float64
 7   embarked     780 non-null    object
 8   class        780 non-null    object
 9   who          780 non-null    object
 10  adult_male   780 non-null    int64
 11  embark_town  780 non-null    object
 12  alive        780 non-null    object
 13  alone        780 non-null    int64
dtypes: float64(2), int64(7), object(5)
memory usage: 91.4+ KB

In [62]:
df['alive']=df['alive'].map({'yes':1,'no':0})

In [63]:
df['alive'].head(10)

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: alive, dtype: int64

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     780 non-null    int64
 1   pclass       780 non-null    int64
 2   sex          780 non-null    int64
 3   age          780 non-null    float64
 4   sibsp        780 non-null    int64
 5   parch        780 non-null    int64
 6   fare         780 non-null    float64
 7   embarked     780 non-null    object
 8   class        780 non-null    object
 9   who          780 non-null    object
 10  adult_male   780 non-null    int64
 11  embark_town  780 non-null    object
 12  alive        780 non-null    int64
 13  alone        780 non-null    int64
dtypes: float64(2), int64(8), object(4)
memory usage: 91.4+ KB

## Encoding

> When a column has more than 2 types of values (unlike boolean or male female etc.), we can't map them to differnet numerical values.

> When we represent a column as 0 and 1, its representation.

> When we represent a column as 0, 1 and 2 or more, it defines priority rather than representation.

> Hence, we don't map values in case of more than 2 unique values (we do when there is actual priority in the unique values. Eg. pclass column of this dataset gives passenger class as first class, second class or third class with first class being top priority). We perform encoding.

We perform One Hot Encoding. Lets take example for 'embarked' column,

*   In 'embarked' column, three categories of values are present. 'C', 'S' and 'Q'.
*   get_dummies() function of pandas library takes a list of columns we need to apply this on.

*   It drops the original column.
*   It makes new columns or dummies, one for each unique value (here 'embarked_C', 'embarked_S' and 'embarked_Q') in alphabetical order.

*   For value 'C' in embarked, the value for 'embarked_C' will be 1 or True and for rest will be 0 or False and so on.

In [65]:
#df=pd.get_dummies(df, columns=['embarked'])

In [66]:
#df.head()

We noticed that we can reduce number of columns by 1 to this as well.

For that we use 'drop_first=True' attribute which removes the first dummy according to alphabetical order (here 'embarked_C').

False and False value for 'embarked_S' and 'embarked_Q' respectively represents the value 'C'.

In [67]:
df=pd.get_dummies(df, columns=['embarked'],drop_first=True)

In [68]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone,embarked_Q,embarked_S
0,0,3,1,22.0,1,0,7.2500,Third,man,1,Southampton,0,0,False,True
1,1,1,0,38.0,1,0,71.2833,First,woman,0,Cherbourg,1,0,False,False
2,1,3,0,26.0,0,0,7.9250,Third,woman,0,Southampton,1,1,False,True
3,1,1,0,35.0,1,0,53.1000,First,woman,0,Southampton,1,0,False,True
4,0,3,1,35.0,0,0,8.0500,Third,man,1,Southampton,0,1,False,True

In [69]:
df=pd.get_dummies(df, columns=['who'],drop_first=True)

In [70]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,adult_male,embark_town,alive,alone,embarked_Q,embarked_S,who_man,who_woman
0,0,3,1,22.0,1,0,7.2500,Third,1,Southampton,0,0,False,True,True,False
1,1,1,0,38.0,1,0,71.2833,First,0,Cherbourg,1,0,False,False,False,True
2,1,3,0,26.0,0,0,7.9250,Third,0,Southampton,1,1,False,True,False,True
3,1,1,0,35.0,1,0,53.1000,First,0,Southampton,1,0,False,True,False,True
4,0,3,1,35.0,0,0,8.0500,Third,1,Southampton,0,1,False,True,True,False

In [71]:
df=pd.get_dummies(df, columns=['embark_town'],drop_first=True)

In [72]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,adult_male,alive,alone,embarked_Q,embarked_S,who_man,who_woman,embark_town_Queenstown,embark_town_Southampton
0,0,3,1,22.0,1,0,7.2500,Third,1,0,0,False,True,True,False,False,True
1,1,1,0,38.0,1,0,71.2833,First,0,1,0,False,False,False,True,False,False
2,1,3,0,26.0,0,0,7.9250,Third,0,1,1,False,True,False,True,False,True
3,1,1,0,35.0,1,0,53.1000,First,0,1,0,False,True,False,True,False,True
4,0,3,1,35.0,0,0,8.0500,Third,1,0,1,False,True,True,False,False,True

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   survived                 780 non-null    int64
 1   pclass                   780 non-null    int64
 2   sex                      780 non-null    int64
 3   age                      780 non-null    float64
 4   sibsp                    780 non-null    int64
 5   parch                    780 non-null    int64
 6   fare                     780 non-null    float64
 7   class                    780 non-null    object
 8   adult_male               780 non-null    int64
 9   alive                    780 non-null    int64
 10  alone                    780 non-null    int64
 11  embarked_Q               780 non-null    bool
 12  embarked_S               780 non-null    bool
 13  who_man                  780 non-null    bool
 14  who_woman                780 non-null    bool
 15  embark_town_Queenstown   780 non-null    bool
 16  embark_town_Southampton  780 non-null    bool
dtypes: bool(6), float64(2), int64(8), object(1)
memory usage: 77.7+ KB

For class column, we will use mapping as we have to set top priority to first class, then second and then third.

In [74]:
df['class']=df['class'].map({'First':3,'Second':2,'Third':1})

In [75]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,adult_male,alive,alone,embarked_Q,embarked_S,who_man,who_woman,embark_town_Queenstown,embark_town_Southampton
0,0,3,1,22.0,1,0,7.2500,1,1,0,0,False,True,True,False,False,True
1,1,1,0,38.0,1,0,71.2833,3,0,1,0,False,False,False,True,False,False
2,1,3,0,26.0,0,0,7.9250,1,0,1,1,False,True,False,True,False,True
3,1,1,0,35.0,1,0,53.1000,3,0,1,0,False,True,False,True,False,True
4,0,3,1,35.0,0,0,8.0500,1,1,0,1,False,True,True,False,False,True

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   survived                 780 non-null    int64
 1   pclass                   780 non-null    int64
 2   sex                      780 non-null    int64
 3   age                      780 non-null    float64
 4   sibsp                    780 non-null    int64
 5   parch                    780 non-null    int64
 6   fare                     780 non-null    float64
 7   class                    780 non-null    int64
 8   adult_male               780 non-null    int64
 9   alive                    780 non-null    int64
 10  alone                    780 non-null    int64
 11  embarked_Q               780 non-null    bool
 12  embarked_S               780 non-null    bool
 13  who_man                  780 non-null    bool
 14  who_woman                780 non-null    bool
 15  embark_town_Queenstown   780 non-null    bool
 16  embark_town_Southampton  780 non-null    bool
dtypes: bool(6), float64(2), int64(9)
memory usage: 77.7 KB

We now need to convert all boolean to numerical. We directly use .replace() function to replace True value to 1 and False value to 0 wherever they occur.

In [77]:
df=df.replace({True:1, False:0}) #Converting all boolean to 1 and 0

/tmp/ipykernel_4411/961798772.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace({True:1, False:0}) #Converting all boolean to 1 and 0

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   survived                 780 non-null    int64
 1   pclass                   780 non-null    int64
 2   sex                      780 non-null    int64
 3   age                      780 non-null    float64
 4   sibsp                    780 non-null    int64
 5   parch                    780 non-null    int64
 6   fare                     780 non-null    float64
 7   class                    780 non-null    int64
 8   adult_male               780 non-null    int64
 9   alive                    780 non-null    int64
 10  alone                    780 non-null    int64
 11  embarked_Q               780 non-null    int64
 12  embarked_S               780 non-null    int64
 13  who_man                  780 non-null    int64
 14  who_woman                780 non-null    int64
 15  embark_town_Queenstown   780 non-null    int64
 16  embark_town_Southampton  780 non-null    int64
dtypes: float64(2), int64(15)
memory usage: 109.7 KB

In [79]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,adult_male,alive,alone,embarked_Q,embarked_S,who_man,who_woman,embark_town_Queenstown,embark_town_Southampton
0,0,3,1,22.0,1,0,7.2500,1,1,0,0,0,1,1,0,0,1
1,1,1,0,38.0,1,0,71.2833,3,0,1,0,0,0,0,1,0,0
2,1,3,0,26.0,0,0,7.9250,1,0,1,1,0,1,0,1,0,1
3,1,1,0,35.0,1,0,53.1000,3,0,1,0,0,1,0,1,0,1
4,0,3,1,35.0,0,0,8.0500,1,1,0,1,0,1,1,0,0,1

Now, we save the clean dataset or dataframe as a new csv file. We give 'index' as False to not include the first Serial No. column.

In [80]:
df.to_csv('Titanic_cleaned.csv',index=False)