In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("PlayTennis.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   outlook   14 non-null     object
 1   temp      14 non-null     object
 2   humidity  14 non-null     object
 3   windy     14 non-null     bool
 4   play      14 non-null     object
dtypes: bool(1), object(4)
memory usage: 594.0+ bytes

In [ ]:
df

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [ ]:
len(df)

14

In [ ]:
df['play'].value_counts()

play
yes    9
no     5
Name: count, dtype: int64

In [ ]:
df['play']

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: play, dtype: object

In [ ]:
df[df['play'] == 'yes']

     outlook  temp humidity  windy play
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
6   overcast  cool   normal   True  yes
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes

In [ ]:
len(df[df['play'] == 'yes'])

9

In [ ]:
P_yes = len(df[df['play'] == 'yes']) / len(df) # P(yes)

In [ ]:
P_yes

0.6428571428571429

In [ ]:
P_no = len(df[df['play'] == 'no']) / len(df) # P(no)

In [ ]:
P_no

0.35714285714285715

In [ ]:
P_cool_yes=len(df[(df['temp'] == 'cool') & (df['play'] == 'yes')]) / len(df[df['play'] == 'yes']) # P( temp=cool / yes)

In [ ]:
P_sunny_yes=len(df[(df['outlook'] == 'sunny') & (df['play'] == 'yes')]) / len(df[df['play'] == 'yes']) # P(outlook=sunny / yes)

In [ ]:
P_sunny_yes

0.2222222222222222

In [ ]:
P_high_yes=len(df[(df['humidity'] == 'high') & (df['play'] == 'yes')]) / len(df[df['play'] == 'yes']) # P(humidity=high / yes)

In [ ]:
P_strong_yes=len(df[(df['windy'] == True) & (df['play'] == 'yes')]) / len(df[df['play'] == 'yes']) # P(windy=True / yes)

In [ ]:
P_yes_final = P_yes * P_sunny_yes * P_cool_yes * P_high_yes * P_strong_yes # P(yes) * P(sunny/yes) * P(cool/yes) * P(high/yes) * P(strong/yes)

In [ ]:
P_yes_final # P(yes / sunny, cool, high, strong)

0.005291005291005291

In [ ]:
P_sunny_no = len(df[(df['outlook'] == 'sunny') & (df['play'] == 'no')]) / len(df[df['play'] == 'no']) # P(outlook=sunny / no)

In [ ]:
P_cool_no = len(df[(df['temp'] == 'cool') & (df['play'] == 'no')]) / len(df[df['play'] == 'no']) # P(temp=cool / no)

In [ ]:
P_high_no = len(df[(df['humidity'] == 'high') & (df['play'] == 'no')]) / len(df[df['play'] == 'no']) # P(humidity=high / no)

In [ ]:
P_strong_no = len(df[(df['windy'] == True) & (df['play'] == 'no')]) / len(df[df['play'] == 'no']) # P(windy=True / no)

In [ ]:
P_no_final = P_no * P_sunny_no * P_cool_no * P_high_no * P_strong_no # P(no) * P(sunny/no) * P(cool/no) * P(high/no) * P(strong/no)

0.02057142857142857

In [ ]:
P_no_final # P(no / sunny, cool, high, strong)

In [ ]:
print("Yes" if P_yes_final > P_no_final else "No")

No

In [ ]:
if P_yes_final > P_no_final :
  print("Yes")
else:
  print("No")

No

USING NAIVE BAYES

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() # can't use one hot encoding as assumption of having independent features will fail

In [ ]:
df_encoded = df.copy()

In [ ]:
df_encoded['outlook'] = le.fit_transform(df_encoded['outlook'])

In [ ]:
df_encoded['temp'] = le.fit_transform(df_encoded['temp'])
df_encoded['humidity'] = le.fit_transform(df_encoded['humidity'])
df_encoded['windy'] = le.fit_transform(df_encoded['windy'])
df_encoded['play'] = le.fit_transform(df_encoded['play'])

In [ ]:
from sklearn.naive_bayes import CategoricalNB

In [ ]:
print(df_encoded['play'])

0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: play, dtype: int64

In [ ]:
model = CategoricalNB()

In [ ]:
model.fit(df_encoded.drop('play', axis=1), df_encoded['play'])

CategoricalNB()

In [ ]:

print(le.classes_)
print

['no' 'yes']

In [ ]:
model.predict([[2, 0,0, 1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(

array([0])

In [ ]:
sample = pd.DataFrame([[2,0,0,1]], columns=['outlook','temp','humidity','windy'])

In [ ]:
prediction = model.predict(sample)

In [ ]:
prediction

array([0])

In [ ]:
result = le.inverse_transform(prediction)
result

array(['no'], dtype=object)